{% set name = "git-credential-manager" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/GitCredentialManager/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: d5f24ed7810b92616db81762869de86e1e0729c628d77c0dd91f4c430a0bf7b0
  patches:
    - 00000-no_self_contained.patch  # [not aarch64 and not arm64]
    - 00001-set_linux_runtime.patch

build:
  skip: true  # [aarch64]
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}  # [linux]
    - dotnet  >=7
    # Make sure that the runtime version is larger than the build version
    - dotnet-runtime =7.0.0
  host:
    - fontconfig  # [linux]
    - zlib  # [aarch64]
  run:
    - dotnet-runtime =7

test:
  requires:
    - git
  commands:
    - git credential-manager --version

about:
  home: https://github.com/GitCredentialManager/git-credential-manager
  summary: Secure, cross-platform Git credential storage
  description: |
    Secure, cross-platform Git credential storage with authentication to
    GitHub, Azure Repos, and other popular Git hosting services.
  license: MIT
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - dhirschfeld
    - sshockwave
