{% set name = "git-credential-manager" %}
{% set version = "2.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/GitCredentialManager/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 12377310a0d47b9ceaabf4bdf2a7e8ef7144dd407248db6935805efaa71326b1
  patches:
    - 00000-no_self_contained.patch  # [not aarch64 and not arm64]
    - 00001-set_linux_runtime.patch

build:
  skip: true  # [aarch64]
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}  # [linux]
    - {{ stdlib("c") }}    # [linux]
    - dotnet =8
    # Make sure that the runtime version is larger than the build version
  host:
    - fontconfig  # [linux]
    - zlib  # [aarch64]
  run:
    - pin_compatible('dotnet-runtime', min_pin='x.x.x', max_pin='x')

test:
  requires:
    - git
  commands:
    - git credential-manager --version

about:
  home: https://github.com/GitCredentialManager/git-credential-manager
  summary: Secure, cross-platform Git credential storage
  description: |
    Secure, cross-platform Git credential storage with authentication to
    GitHub, Azure Repos, and other popular Git hosting services.
  license: MIT
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - dhirschfeld
    - sshockwave
