{% set name = "git-credential-manager" %}
{% set version = "2.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/GitCredentialManager/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: a9c1d7a89c620bea0df65623f25c62e66122d22557583ab390ed612d544884e9
  patches:
    - 00000-no_self_contained.patch  # [not aarch64 and not arm64]
    # This fixes the call to string.Split(), needed for .NET 8.0 but not for .net 4.7.
    # When the Windows version upgrades .NET version,
    # we can apply this fix to all platforms.
    # This fix is also tracked in the upstream.
    - 00001-fix_ambiguous_call_to_string_split.patch  # [not win]

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}  # [linux]
    - {{ stdlib("c") }}    # [linux]
    - dotnet =8.0.100
  host:
    - fontconfig  # [linux]
    - zlib  # [aarch64]
  run:
    - dotnet-runtime =8

test:
  requires:
    - git
  commands:
    - git credential-manager --version

about:
  home: https://github.com/GitCredentialManager/git-credential-manager
  summary: Secure, cross-platform Git credential storage
  description: |
    Secure, cross-platform Git credential storage with authentication to
    GitHub, Azure Repos, and other popular Git hosting services.
  license: MIT
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - dhirschfeld
    - sshockwave
