{% set name = "git-credential-manager" %}
{% set version = "2.1.0" %}
{% set dotnet_version = "6.0.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/git-ecosystem/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: c51594f6fc06860a8cf81d7bb55a41856be83cc5bba1d3fc131f226d4fd03690
  - url: https://github.com/git-ecosystem/{{ name }}/releases/download/v{{ version }}/{{ name }}.{{ version }}.nupkg
    fn: {{ name }}.{{ version }}.nupkg
    sha256: 8a362204d3f5ef1b0774dcdf768fa3be12e9209cf7fc224f3435625d6b94b28e

build:
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}  # [linux]
    - dotnet
    - dotnet-runtime ={{ dotnet_version }}
  run:
    - dotnet-runtime >={{ dotnet_version }},<7

test:
  requires:
    - git
    - dotnet-runtime ={{ dotnet_version }}
  commands:
    - git credential-manager --version

about:
  home: https://github.com/GitCredentialManager/git-credential-manager
  summary: Secure, cross-platform Git credential storage
  description: |
    Secure, cross-platform Git credential storage with authentication to
    GitHub, Azure Repos, and other popular Git hosting services.
  license: MIT
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - dhirschfeld
