{% set name = "git-credential-manager" %}
{% set version = "2.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/GitCredentialManager/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: cb914389f2854f969911bca85fdce2f95eabd2227b32cea802dbce60e2793997
  patches:
    - 00000-no_self_contained.patch  # [not aarch64 and not arm64]
    - 00001-set_linux_runtime.patch

build:
  skip: true  # [aarch64]
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}  # [linux]
    - dotnet  >=7
    # Make sure that the runtime version is larger than the build version
    - dotnet-runtime =7.0.0
  host:
    - fontconfig  # [linux]
    - zlib  # [aarch64]
  run:
    - dotnet-runtime =7

test:
  requires:
    - git
  commands:
    - git credential-manager --version

about:
  home: https://github.com/GitCredentialManager/git-credential-manager
  summary: Secure, cross-platform Git credential storage
  description: |
    Secure, cross-platform Git credential storage with authentication to
    GitHub, Azure Repos, and other popular Git hosting services.
  license: MIT
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - dhirschfeld
    - sshockwave
