{% set name = "git-credential-manager" %}
{% set version = "2.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/GitCredentialManager/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 9f7fc2b95cdf82c6bebeb045a553ed27c0130f426bc840e4f2dc41cbb27b6c31
  patches:
    - 00000-no_self_contained.patch  # [not aarch64 and not arm64]

build:
  skip: true  # [aarch64]
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}  # [linux]
    - {{ stdlib("c") }}    # [linux]
    - dotnet =8.0.100
  host:
    - fontconfig  # [linux]
    - zlib  # [aarch64]
  run:
    - dotnet-runtime =8

test:
  requires:
    - git
  commands:
    - git credential-manager --version

about:
  home: https://github.com/GitCredentialManager/git-credential-manager
  summary: Secure, cross-platform Git credential storage
  description: |
    Secure, cross-platform Git credential storage with authentication to
    GitHub, Azure Repos, and other popular Git hosting services.
  license: MIT
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - dhirschfeld
    - sshockwave
