{% set name = "git-credential-manager" %}
{% set version = "2.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/GitCredentialManager/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 2593df909f83ae68a9f01bc02d9e21476b94884d035aa9018496c3ebd7d89846
  patches:
    - 00000-no_self_contained.patch  # [not aarch64 and not arm64]
    - 00001-set_linux_runtime.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}  # [linux]
    - dotnet  >=6
  host:
    - fontconfig  # [linux]
    - zlib  # [aarch64]
  run:
    - dotnet-runtime =6

test:
  requires:
    - git
  commands:
    - git credential-manager --version

about:
  home: https://github.com/GitCredentialManager/git-credential-manager
  summary: Secure, cross-platform Git credential storage
  description: |
    Secure, cross-platform Git credential storage with authentication to
    GitHub, Azure Repos, and other popular Git hosting services.
  license: MIT
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - dhirschfeld
    - sshockwave
