{% set name = "git-credential-manager" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/GitCredentialManager/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: c51594f6fc06860a8cf81d7bb55a41856be83cc5bba1d3fc131f226d4fd03690
    patches:
      - 00001-set_linux_runtime.patch
      - 00002-target_win64.patch

build:
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}  # [linux]
    - dotnet  >=6
  host:
    - fontconfig  # [linux64]
    - zlib  # [linux64]
  run:
    - dotnet-runtime  >=6

test:
  requires:
    - git
  commands:
    - git credential-manager --version

about:
  home: https://github.com/GitCredentialManager/git-credential-manager
  summary: Secure, cross-platform Git credential storage
  description: |
    Secure, cross-platform Git credential storage with authentication to
    GitHub, Azure Repos, and other popular Git hosting services.
  license: MIT
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - dhirschfeld
