{% set name = "git-credential-manager" %}
{% set version = "2.0.886" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/GitCredentialManager/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 8e07dccabfc4af5d0e82a0657c16e3858fd88995b181b9be86ffcdaa399e7f4c

build:
  skip: true  # [not linux64]
  script: |
    set -eoux pipefail
    # Set correct install location
    sed -i -E 's|^\s*INSTALL_LOCATION="(.*)"$|    INSTALL_LOCATION="${PREFIX}"|g' ./src/linux/Packaging.Linux/build.sh
    # Set the correct version
    echo $(jq '.version = "{{ version }}"' version.json) > version.json
    # Build app
    dotnet build ./src/linux/Packaging.Linux/Packaging.Linux.csproj -c Release -p:InstallFromSource=true
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - dotnet  >=6
    - jq
  host:
    - fontconfig
    - lttng-ust              # [linux64]
    - zlib                   # [unix]
  run:
    - dotnet-runtime  >=6
    - krb5                   # [unix]
    - lttng-ust              # [linux64]

test:
  requires:
    - git
  commands:
    - git-credential-manager-core --version

about:
  home: https://github.com/GitCredentialManager/git-credential-manager
  summary: Secure, cross-platform Git credential storage
  description: |
    Secure, cross-platform Git credential storage with authentication to
    GitHub, Azure Repos, and other popular Git hosting services.
  license: MIT
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - dhirschfeld
